# Site
name: 'dentiumistanbul'
description: 'dentiumistanbul.com'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'info@dentiumistanbul.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    dentiumistanbul:
      name:           Dentiumistanbul
      site:           https://www.dentiumistanbul.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "dentiumistanbul.com"
      email:          info@dentiumistanbul.com
      # twitter:        https://twitter.com/dentiumistanbul

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]